docker-compose.yml, phpunit.sh, src/Keboola/DbExtractor/Extractor/PgSQL.php, tests/Keboola/Extractor/PgsqlTest.php
ref: https://github.com/keboola/db-extractor-pgsql/issues/6
=> use client-side \copy command

composer.lock
Updatunty ssh tunnel https://github.com/keboola/ssh-tunnel/pull/2
souvisí s https://github.com/keboola/syrup-router/issues/50
=> fix - ssh tunnel update - ssh keep alive

Dockerfile, docker-compose.yml, phpunit.sh, src/Keboola/DbExtractor/Extractor/PgSQL.php, tests/Keboola/Extractor/PgsqlTest.php
2nd try at this one.  Have test config ready to go (ref: https://github.com/keboola/connection/issues/858)
=> \copy command 2

src/Keboola/DbExtractor/Extractor/PgSQL.php, tests/Keboola/Extractor/ApplicationTest.php, tests/Keboola/Extractor/PgsqlTest.php, tests/data/pgsql/config.yml
re: https://github.com/keboola/db-extractor-pgsql/issues/14
=> Support for metadata for foreign keys

composer.lock, src/Keboola/DbExtractor/Extractor/PgSQL.php
update to `db-extractor-common` 5.2.4
=> Common lib update

run.php, src/Keboola/DbExtractor/Extractor/PgSQL.php, tests/Keboola/Extractor/ApplicationTest.php, tests/Keboola/Extractor/PgsqlTest.php
=> tables with the same name

.travis.yml, composer.json, composer.lock, docker-compose.yml, phpcs.xml, phpunit.xml.dist, run.php, src/Keboola/DbExtractor/Extractor/PgSQL.php, tests/Keboola/Extractor/ApplicationTest.php, tests/Keboola/Extractor/PgsqlTest.php, tests/data/pgsql/config.json, tests/data/pgsql/config.yml, tests/data/pgsql/escaping.csv
Fixes: #2 #19 and #22 
Partially Fixes #23
=> Update to latest common library

src/Keboola/DbExtractor/Extractor/PgSQL.php, tests/Keboola/Extractor/PgsqlTest.php
=> Improve performance of getTables action

src/Keboola/DbExtractor/Extractor/PgSQL.php, tests/Keboola/Extractor/PgsqlTest.php
=> Remove foreign key meta

src/Keboola/DbExtractor/Extractor/PgSQL.php, tests/Keboola/Extractor/PgsqlTest.php
=> Fix broken error handling

Dockerfile
=> Remove php memory limit

run.php, src/Keboola/DbExtractor/Configuration/PgsqlConfigRowDefinition.php, src/Keboola/DbExtractor/Extractor/PgSQL.php, src/Keboola/DbExtractor/PgsqlApplication.php, tests/Keboola/Extractor/BaseTest.php, tests/Keboola/Extractor/IncrementalFetchingTest.php
=> Use forceFallback to test incremental fetching state bug

src/Keboola/DbExtractor/Extractor/PgSQL.php, tests/Keboola/Extractor/PgsqlTest.php
This should reduce execution time somewhat for the getTables request.
=> use single query to getTables

src/Keboola/DbExtractor/Extractor/PgSQL.php, tests/Keboola/Extractor/PgsqlTest.php
hopefully fixes https://github.com/keboola/internal/issues/198
=> use \copy for getTables

src/Keboola/DbExtractor/Extractor/PgSQL.php, tests/Keboola/Extractor/PgsqlTest.php
fixes #63 
Reasons:
- did not solve the timeout issue for VN network (even though there was good performance improvement)
- caused unreproducible issue #63
=> revert using \copy for getTables

src/Keboola/DbExtractor/Extractor/PgSQL.php, tests/Keboola/Extractor/BaseTest.php, tests/Keboola/Extractor/IncrementalFetchingTest.php, tests/Keboola/Extractor/PgsqlTest.php
fixes #67 
so far just the test is here.
=> fix for dropped columns breaking incr fetch

src/Keboola/DbExtractor/Configuration/PgsqlGetTablesDefinition.php, tests/Keboola/Extractor/ApplicationTest.php
=> ignore extra keys on getTables request

src/Keboola/DbExtractor/Extractor/PgSQL.php
=> use retry proxy for all queries

src/Keboola/DbExtractor/Extractor/PgSQL.php
=> Throw reconnection exceptions as user errors

composer.lock, run.php
Update db-extractor-common
Catch ConfigUserException - Solves https://github.com/keboola/db-extractor-common/issues/131
=> Catch config exception and update common

composer.lock, src/Keboola/DbExtractor/Extractor/PgSQL.php, tests/Keboola/Extractor/ApplicationTest.php
Solving https://github.com/keboola/db-extractor-common/issues/128
=> Check connecting via ssh tunnel

docker-compose.yml, src/Keboola/DbExtractor/Extractor/PgSQL.php
Fixes: #86 
Changes:
- Copy of PR #86
=> Fix removed obsolete pg_attrdef.adsrc

src/Keboola/DbExtractor/Extractor/PgSQL.php
Fixes bug - https://keboola.atlassian.net/browse/COM-66
=> fixup getTables sql statement

.travis.yml, docker-compose.yml
Solving - https://github.com/keboola/db-extractor-pgsql/pull/89#pullrequestreview-325129475
=> Tests on old server version

composer.json, composer.lock, src/Keboola/DbExtractor/Extractor/PgSQL.php
Missing method for get max incremental value
=> Method for max increment max value

composer.json, composer.lock, src/Keboola/DbExtractor/PgsqlApplication.php
Part of - https://keboola.atlassian.net/browse/COM-49
=> Recognition config row

Dockerfile, composer.json, composer.lock, tests/Keboola/Extractor/BaseTest.php
Solving part of https://keboola.atlassian.net/browse/COM-27
=> Update php to version 7.4

src/Keboola/DbExtractor/Extractor/PgSQL.php, tests/Keboola/Extractor/BaseTest.php, tests/Keboola/Extractor/GetTablesTest.php, tests/Keboola/Extractor/PgsqlTest.php
Solving - https://keboola.atlassian.net/browse/COM-97
=> test for PDO export empty table

composer.json
=> wait-for-it pgsql

composer.json, composer.lock, tests/Keboola/Extractor/BaseTest.php
fixes - https://keboola.slack.com/archives/C035LGNK5/p1578321554009700
=> add index on table column

src/Keboola/DbExtractor/Extractor/PgSQL.php, tests/Keboola/Extractor/ApplicationTest.php
Solving - https://keboola.atlassian.net/browse/COM-188
Discussion - https://keboola.slack.com/archives/CFVRE56UA/p1581501661029300
=> Export table manifest only with data rows > 0

src/Keboola/DbExtractor/Extractor/PgSQL.php, tests/Keboola/Extractor/ApplicationTest.php
Solving result - https://keboola.slack.com/archives/CFVRE56UA/p1581501661029300
=> remove csv file if empty export data

composer.json, composer.lock, src/Exception/CopyAdapterConnectionException.php, src/Exception/CopyAdapterException.php, src/Exception/CopyAdapterQueryException.php, src/Extractor/CopyAdapter.php, src/Extractor/PDOAdapter.php, src/Extractor/PgSQL.php, src/Extractor/PgSQLMetadataProvider.php, tests/phpunit/ApplicationTest.php, tests/phpunit/IncrementalFetchingTest.php, tests/phpunit/PgsqlTest.php
Changes:
- Main problem was this part of code (`extract`) method:
https://github.com/keboola/db-extractor-pgsql/blob/dbc775e3168198f855754c1c2e5ef0beda3c7f56/src/Extractor/PgSQL.php#L128-L201
- It is very difficult to refactor it without error to value objects, as there are many nested try / catch blocks + a bunch of conditions.
- Therefore was code divided into:
-  `CopyAdapter` (export using `psql` cli tool and `\copy` command) and 
- `PdoAdapter` (export using PDO)
=> Simplified code, created CopyAdapter and PdoAdapter

src/Extractor/CopyAdapter.php
Changes:
- Before refactoring was timeout set to `null` for `Copy` operation:
https://github.com/keboola/db-extractor-pgsql/blob/3ecc96343492485f1c375d486d588c99308b61b8/src/Keboola/DbExtractor/Extractor/PgSQL.php#L340
- But during refactoring, this line was accidentally removed.
=> Fix missing timeout=null

src/Configuration/PgsqlTableNodeDecorator.php, tests/phpunit/PgsqlTest.php
Solving - https://keboola.atlassian.net/browse/COM-314
=> Config with empty primaryKey string

src/Extractor/PgSQLMetadataProvider.php
Solving - https://keboola.atlassian.net/browse/COM-324
=> empty tyble type not set in metadataBuilder

src/Extractor/CopyAdapter.php
Refactoring process command string
=> Refactoring process command

.github/workflows/push.yml
Jira - https://keboola.atlassian.net/browse/COM-933
=> Add docker login

.github/workflows/push.yml
Při psaní intra na GH actions jsem přišel na lepší způsob jak napsat workflow pro různé verze PgSQL serveru
=> better GH actions workflow

.gitignore, Dockerfile, deploy.sh, docker-compose.yml, src/Extractor/CopyAdapter.php, src/Extractor/PgSQLConnectionFactory.php, src/Extractor/PgSQLDsnFactory.php
Jira: https://keboola.atlassian.net/browse/COM-1036
=> Fix SSL connection

composer.json, composer.lock, tests/functional/ssl-test-connection/source/data/config.json
Jira: https://keboola.atlassian.net/browse/COM-1044
=> Make config key 'ssl.key' secret

.github/workflows/push.yml
Changes:
- Simplified GH action.
=> Simplify GH workflow

README.md
just add `useConsistentFallbackBooleanStyle` and `forceFallback` to README
=> Add PDO settings to readme

src/Extractor/CopyAdapterQueryMetadata.php
JIRA: https://keboola.atlassian.net/browse/CM-477
=> Convert PDOException to UserException in CopyAdapterQueryMetadata

composer.json, composer.lock
Jira - https://keboola.atlassian.net/browse/CM-619
=> update keboola/db-extractor-config package

src/Extractor/PgSQLMetadataProvider.php, tests/functional/get-tables-action/setUp.php
JIRA: https://keboola.atlassian.net/browse/CM-691
Failující test před opravou: https://github.com/keboola/db-extractor-pgsql/actions/runs/5764845855
=> Remove sequences from get tables

Dockerfile
Jira: https://keboola.atlassian.net/browse/CM-797
See: https://keboola.atlassian.net/browse/CM-797?focusedCommentId=79418
Changes:
- Set `ENV PGOPTIONS="-c client_min_messages=ERROR"`.
- It prevents `LOG: ` from Azure managed PgSQL instances to break `testConnection` synchronous action.
=> Set client_min_messages=ERROR to prevent server side debugging mesages

composer.lock, phpstan-baseline.neon, src/Configuration/NodeDefinition/PgsqlTableNodeDecorator.php, src/Extractor/PgSQLMetadataProvider.php
JIRA: 
- https://keboola.atlassian.net/browse/PST-1996
- https://keboola.atlassian.net/browse/PST-2025
SLACK: https://keboolaglobal.slack.com/archives/C055HSMKX51/p1723642181597589?thread_ts=1723214328.361609&cid=C055HSMKX51
=> Update db-extractor-common to latest version which fails when trying to set PK on non-existing column (case insensitive)

.github/workflows/push.yml, Dockerfile
Jira - https://keboola.atlassian.net/browse/PST-2120
=> PGOPTIONS has own docker image

Dockerfile, docker/ssh-config
https://keboola.atlassian.net/browse/SUPPORT-9608
=> fix rsa pubkey type for ssh tunnel
